### ISSUE TITLE
Technical RoadMap for contributive framework

### ISSUE THREAD

**Issue by cbeauchesne** [cbeauchesne/campui#102]
* [ ] API option for articles `?mode=raw&l=<lang>`
* [ ] modify index.html to read custom.js and custom.css
* [ ] modify app.js to read portal factory in custom.js
* [ ] do custom.js
  * Factory 
    * .portals : [{name, article_id, icon}]
* [ ] do portal view : simple angular template from `article/article_id?mode=raw&l=<lang>`
* [ ] Add portals list in navbar
* [ ] create first portal : Main_page/Acceuil
